development:
  adapter: postgresql
  #host: localhost
  encoding: unicode
  database: ocr_development
  pool: 5
  username: franciscorenteria
  password:
    
test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: ocr_test
  pool: 5
  username: franciscorenteria
  password: