development:
  adapter: postgresql
  #host: localhost
  encoding: unicode
  database: quicktalk_development
  pool: 5
  username: franciscorenteria
  password:
    
test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: quicktalk_test
  pool: 5
  username: franciscorenteria
  password: